### ISSUE TITLE
ENGIE - Not the same number of jobs on scraper and https://jobs.engie.com

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#13]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Engie.
3. Click on Engie folder.
4. Click on "Run Scraper" button.
5. Check the number of jobs.

EXPECTED RESULT:
The city is displayed

- Technical Trainee @ENGIE Servicii - Bucuresti
- Junior Salesforce Technical Consultant - Bucharest
- Consilier vanzari energie si servicii- Giurgiu- perioada determinata - GIURGIU
- Consilier vanzari energie si servicii- Constanta- perioada determinata - Constanta
- Consilier vanzari energie si servicii - Mall Baneasa Bucuresti - Bucuresti
- Internal Auditor - Bucuresti
- Consilier vanzari energie și servicii - Craiova
- Agent de Teren Promovare Invatamant Dual ENGIE - Craiova
- Electrician - Bucuresti
- Diriginte de santier - Bucuresti, Brasov, Craiova
- Specialist Tehnic Distributie - Bucuresti, Buzau
- Instalator Autorizat ANRE - Bucuresti, Buzau, Galati, Craiova
- Inginer Instalatii Gaze / Centrale Termice - Bucuresti, Buzau, Galati,

ACTUAL RESULT:
57 jobs are displayed

![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/5fadebfe-a4a3-4549-9d51-25d23d8ee90d)

**Comment by IurieChi** [comment]
hi, you can close this issue. I've created a new scraper and now is ok.
