### ISSUE TITLE
EXIGER -  0 Jobs are displayed

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#14]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Exiger.
3. Click on Exiger folder.
4. Click on "Run Scraper" button.
5. Check the number of jobs.

EXPECTED RESULT:
6 jobs are displayed:

- Analyst, Research & Delivery, Managed Services (Chinese/Russian) - Bucharest
- Associate, Research & Delivery (Arabic) - Bucharest
- Associate, Research & Delivery (English + different language) - Bucharest
- Interviewer/Researcher with Russian - Bucharest
- Analyst, QC Layer - Managed Services - Bucharest
- Data Analyst - Bucharest

ACTUAL RESULT:
0 jobs are displayed

![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/519210c3-a224-4431-a4e3-c71b19ffb5f3)

**Comment by IurieChi** [comment]
please assign this bug to me I will check
