### ISSUE TITLE
EXPRESSOFT - "Careers" button

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#15]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Expressoft.
3. Click on Expressoft. folder.
4. Click on "Run Scraper" button.
5. Click on "Careers" button

EXPECTED RESULT:
Careers page is displayed (https://expressoft.ro/cariere/)

ACTUAL RESULT:
Antother https://scrapers.peviitor.ro/src/expressoft/index.html opens.

![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/75208f6c-14f6-4038-91d9-4612623daec3)

**Comment by IurieChi** [comment]
hi, you can close this issue fixed
