### ISSUE TITLE
EXPRESSOFT - "Romania is not a city in Romania"

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#16]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Expressoft.
3. Click on Expressoft folder.
4. Click on "Run Scraper" button.
5. Check city of jobs.

EXPECTED RESULT:
The city is displayed

ACTUAL RESULT:
Error: "Romania is not a city in Romania"
![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/a78cc659-07f1-4adc-a0e1-ef04765dcfc2)

**Comment by IurieChi** [comment]
hi, you can close this issue fixed
