### ISSUE TITLE
BRINEL - Jobs are not displayed

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#5]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Brinel.
3. Click on Brinel folder.
4. Click on "Run Scraper" button.
5. Check the logo.

EXPECTED RESULT:

- Sales Support Representative FSI: Bucuresti
- Sales Account Executive: Cluj-Napoca
- Technical Pre-Sales Engineer: Bucuresti 
- Developer Microsoft Dynamics 365 Finance and Operations AX 2012: 
- Consultant Microsoft Dynamics 365 Finance and Operations AX
- AWS DevOPS Cloud Engineer
- Microsoft Presales Specialist: Cluj-Napoca
- Sales Executive IT Infrastructure: Bucuresti 
- Network Engineer: Cluj-Napoca 
- Servers and Storage Engineer: Cluj-Napoca
- Product Manager Software

**Comment by IurieChi** [comment]
solved you can close this bug
