### ISSUE TITLE
CODEZILLA - "Remote is not a city in Romania"

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#7]
ENVIRONMENT : Production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Codezilla.
3. Click on Codezilla folder.
4. Click on "Run Scraper" button.
5. Check city of jobs.

EXPECTED RESULT:
No city.

ACTUAL RESULT:
"Remote is not a city in Romania" is displayed.
![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/f7cf2b7f-528d-40e5-8818-b3b61e088c24)

**Comment by IurieChi** [comment]
Issue solved close this bug

**Comment by IurieChi** [comment]
Issue solved close this bug
