### ISSUE TITLE
CODEZILLA - Jobs not found on www.peviitor.ro

### ISSUE THREAD

**Issue by simina1606** [peviitor-ro/Scrapers_Job_PeViitor#8]
ENVIRONMENT : Production
URL: https://www.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open Url in browser.
2. Write in search bar : Codezilla.
3. Click on "Cauta" button

EXPECTED RESULT:
Jobs are displayed.

ACTUAL RESULT:
0 jobs are displayed.

![image](https://github.com/peviitor-ro/Scrapers_Job_PeViitor/assets/156781906/def58ebd-e904-4980-b870-0ff79d0be111)

**Comment by IurieChi** [comment]
Issue solved close this bug
